 Volume in drive C has no label.
 Volume Serial Number is C4E8-AD4F

 Directory of C:\Users\Administrator\Documents\JAVAProjects

06/12/2019  10:28 AM    <DIR>          .
06/12/2019  10:28 AM    <DIR>          ..
06/12/2019  09:22 AM               418 Hello.class
06/12/2019  09:06 AM               115 Hello.java
06/12/2019  10:28 AM                 0 index.http
               3 File(s)            533 bytes
               2 Dir(s)  21,603,692,544 bytes free
